language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: linux
      sudo: required
      python: 3.4
    - os: linux
      sudo: required
      python: 3.5
    - os: linux
      sudo: required
      python: 3.6
    # HACK this covers python 2.7 by default
    # TODO be explict about OS X Python version
    - os: osx
      language: generic

# TODO: test multiple python versions on OSX https://github.com/travis-ci/travis-ci/issues/2312

before_install:
  - pip install pytest
  - echo $(python --version)

install:
  - travis_retry pip install .

script:
  - pytest

