# use miniconda for python, so don't specify "python", which doesn't
# work on travis osx anyway
language: generic
os:
  - linux

services:
  - docker

sudo: required

matrix:
  fast_finish: true

before_install:
  - docker pull ubuntu:latest

script:
  - docker run --cap-add=SYS_PTRACE -v "$PWD":/travis quiltdata/win64 'conda install --yes pyarrow -c conda-forge & cd travis & pip install . & pytest'
