language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: linux
      sudo: required
      python: 3.3
    - os: linux
      sudo: required
      python: 3.4
    - os: linux
      sudo: required
      python: 3.5
    - os: linux
      sudo: required
      python: 3.6
    - os: osx
      language: generic
      env: TOXENV=py2
    - os: osx
      language: generic
      env: TOXENV=py3

before_install:
  - pip install pytest
  # tox for env management
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install tox; fi
  # install python
  - if [[ "$TOXENV" == "py2" ]]; then brew install python; fi
  - if [[ "$TOXENV" == "py3" ]]; then brew install python3; fi
  # Install HDF5
  # travis_retry here because occasionally fails on high latency
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_retry brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/science/hdf5@1.8; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export HDF5_DIR=$(brew --prefix homebrew/science/hdf5@1.8); fi
  # apt-get libhdf5-dev doesn't work in spite of https://github.com/travis-ci/apt-package-whitelist/issues/416
  # see also: https://github.com/travis-ci/apt-package-whitelist/issues/416
  # right now this looks like the best HDF5 bet
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libhdf5-serial-dev; fi
  - echo $(python --version)

install:
  - pip install .

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tox -e $TOXENV; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pytest; fi

